### ISSUE TITLE
compilation: analyzelogmalloc

### ISSUE THREAD

**Issue by frozar** [qgears/log-malloc-simple#1]
The _README.md_ file does not provide a procedure to compile the _analyzelogmalloc_ visualizer.
It is possible that the provided source files in the repository are not enough to achieve its compilation.

Is it possible that you fix it please? If not, can you give some pictures generated by you tool please?

**Comment by rizsi** [comment]
My colleague and I have updated the README.md file with instructions to build and run the analyser using Eclipse IDE. Example output is also added to the README so you can see what you can expect from the tool. We are planning to implement a Maven build script that automates the build of the analyser.jar and also upload the java binary to our company server.

**Comment by chreex** [comment]
Maven-based build of the analyzer is ready, README.md has been extended with the build instructions.
